server:
    port: 8089
spring:
    datasource:
        url: jdbc:dm://192.168.0.122:5236/TEST?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: SYSDBA
        password: SYSDBA
        driver-class-name: dm.jdbc.driver.DmDriver
#        ConnectionTestQuery: SELECT 1
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dc.entity